[package]
name = "agents"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
ignore = "0.4"
globset = "0.4"
similar = "2.5"
owo-colors = "4"
languages = "0.0.2"

[dev-dependencies]
tempfile = "3"
